# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: publish github page

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: build 
      run: npm install
    - run: npm run build

    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_SSH_KEY }} 
        ARGS: -rltgoDzvO --delete
        SOURCE: /docs
        REMOTE_HOST: gogmap.com
        REMOTE_USER: ${{secrets.ROMETO_USER}}
        TARGET: ${{secrets.TARGET_FOLDER}} # 远程目录

      # with: 
      #     ACCESS_TOKEN: ${{ secrets.PUBLISH }} # VUE_ADMIN_TEMPLATE 是我的 secret 名称，需要替换成你的
      #     BRANCH: master
      #     FOLDER: dist
      #     REPOSITORY_NAME: hanks-tan/covid-19-map/ # 这是我的 github page 仓库
      #     TARGET_FOLDER: docs

